### PR TITLE
Change ser_de to serde

### PR DESCRIPTION
**Pull request by mfadhlika**
gstreamer-rs rename ser_de feature to serde

### CODE REVIEW

**Comment by sdroege** [comment]
You'll also have to update the `Cargo.lock` then, or otherwise it won't compile.

**Comment by mfadhlika** [comment]
right, sorry about that. I've updated the `Cargo.lock`

**Review by sdroege — APPROVED** [review]

**Comment by MathieuDuponchelle** [comment]
lgtm, @mfadhlika can you fix those commits up together? I'll merge then :)

**Comment by mfadhlika** [comment]
done

**Comment by MathieuDuponchelle** [comment]
Thanks!

**Pull request merged**
