### PR TITLE
gcc: Only log error when pausing task failes

### PR DESCRIPTION
**Pull request by thiblahute**
We can't do much about it at this point

Fixes https://github.com/centricular/webrtcsink/issues/110

### CODE REVIEW

**Comment by MathieuDuponchelle** [comment]
The only reason pause_task can return False is when the pad had no task apparently, how can this be happening?

**Comment by MathieuDuponchelle** [comment]
Also I notice that we might pause while holding the state lock, that's not ideal (and something I fixed in mccparse / sccparse some time ago)

**Comment by MathieuDuponchelle** [comment]
2131d5bfda964a062127ed859ce8d28e17f0e450 in gst-plugins-rs fwiw

**Comment by MathieuDuponchelle** [comment]
scratch that last remark, I think we always release actually :)

**Comment by thiblahute** [comment]
> The only reason pause_task can return False is when the pad had no task apparently, how can this be happening?

From the stack trace this happened when pushing the buffer list failed, I guess the task is already stopped from some other code path and is being joined?

**Comment by MathieuDuponchelle** [comment]
I see, then let's just ignore altogether and not log an error :)

**Comment by MathieuDuponchelle** [comment]
elsewhere in `gst-plugins-rs` we just `let _ = pause_task`, let's just do the same here :)

**Comment by MathieuDuponchelle** [comment]
Thanks :)

**Pull request merged**
